model_list:
  - model_name: claude-haiku-4.5
    litellm_params:
      model: anthropic/claude-haiku-4-5-20251001
      api_key: os.environ/ANTHROPIC_API_KEY
      temperature: 0.1
      rpm: 45

  - model_name: victim-llama
    litellm_params:
      model: openai/llama3
      api_base: http://127.0.0.1:8080/v1
      api_key: not-needed

  - model_name: bf16-llama
    litellm_params:
      model: openai/llama3
      api_base: http://127.0.0.1:8081/v1
      api_key: not-needed
      temperature: 0.1

litellm_settings:
  num_retries: 10
  request_timeout: 1080
  allowed_fails: 10
  cooldown_time: 120
